### ISSUE TITLE
Add python code to launch macros

### ISSUE THREAD

**Issue by osso73** [fpindado/iWom-inator#1]
Hi,

the idea is to develop a small script with python that will check the day of the week, and launch the appropriate macro (e.g. L-J, or V version). Later we can add further complexity, such as using several logins and passwords for several people, or filling data for several days -- to be discussed in separate issue.

Oriol

**Comment by fpindado** [comment]
Ok, adelante

**Comment by osso73** [comment]
Paid version of iMacros is required to access the API (e.g. launch the macro from python or similar). Seer https://imacros.net/store/compare-versions/

So we can maybe automate the whole access with python, not using iMacros.

**Comment by osso73** [comment]
I'll close this issue, and open a new one for the python code.
