### ISSUE TITLE
Change Web Elements after applicaiton update

### ISSUE THREAD

**Issue by fpindado** [fpindado/iWom-inator#24]
After iWom application update one web element has changed its name

MainContent_LVportalapps_ctrl0_imgLogo_App_0

Has changed to

MainContent_lblSubtitulo_app4

**Comment by fpindado** [comment]
It's locate in line 230 in script iWom-update.py

**Comment by osso73** [comment]
Ok done. Created branch python_update with new code.

I also updated the webdriver for Edge browser, and removed support for IE, as it is running out of support and the code did not work very well.

I will now create a pull request for that change.
